### ISSUE TITLE
Network display interaction details in "dock"

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#12]
When user hovers over any link, change the style (thicker width?, change cursor pointer) so user is aware they can interact with it. 

When user clicks on any link, somewhere on the page show a "dock" component with:
- source and target taxons (maybe the cards?)
- study name with link to study details where the interaction was observed.
- if there's lat/lng data available, build link to map view

Additional http calls will be required to fetch this data. For example card data (image and common name comes from the image api). The study and lat/lng comes from interaction api where both source and target are specified.

To get all this data in, change layout to container-fluid and 3/6/3 columns.
![image](https://cloud.githubusercontent.com/assets/2428282/6999391/45a5e5a4-dbd7-11e4-86c1-ad2aaacbdc72.png)

**Comment by psmacmur** [comment]
Great idea: just show the cards on the right!  They'll be flippable in a PR or two...

**Comment by danielabar** [comment]
In addition to cards, somehow also need to show:
- Study title (clickable to Study url if that's populated, sometimes its null)
- Or multiple of study title/urls if there are more than one
- If there's also lat/lng, then generate link to the map view
