### ISSUE TITLE
Network enforce max levels

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#15]
The column network graph is laid our horizontally given the width of the graph vis area and a max number of levels. However, the max is not actually enforced so user could keep clicking and generating nodes that go off the visible area.

Add some logic, in the network controller that receives the node click events to check the level of the node that was just clicked, if it exceeds max level, display some explanatory message.

**Comment by psmacmur** [comment]
Or, drop the first level... ?

**Comment by danielabar** [comment]
My brain might explode...

**Comment by psmacmur** [comment]
In that case, how about one of those toasts with that Gandalf quote about the dwarves of Moria who dug too deep?

**Comment by danielabar** [comment]
Works for me, just reply with the text and consider it done ;-)

**Comment by danielabar** [comment]
So thinking more seriously about this, the easiest thing from a technical perspective is to use the toaster library we already have a pop a message. However, that's a bad user experience for several reasons:

* user may not have a chance to read or absorb the meaning of the message before the toaster disappears
* user will feel "stuck" because they really wanted to search on that taxon and it's not obvious how to do so.

So I have a better idea, which is I've already got work in progress: If user clicks on a max level node, present a modal with an explanatory message AND a button they can click to start a new search for their selected taxon and interaction type.

Using [UI Bootstrap Modal](https://angular-ui.github.io/bootstrap/#/modal), its pretty easy to pass scope data to construct a dynamic message like "search for tuna eats".

I hope this will be a better experience for the user, who wishes to explore the graph deeper.

**Comment by psmacmur** [comment]
Oh yeah, if that's quick to implement, it'd be much less frustrating
