### ISSUE TITLE
Incorporate Bipartite graph

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#16]
As part of this #IVMOOC 2015 Globi project, @ritec has built an interactive visualization of species interactions using geo co-ordinates bounding box, together with a map drag & drop style interaction, that generate a bipartite graph. 

Incorporate @ritec 's vis into this project. The "quick & dirty" way, as suggested by @psmacmur will be to add a view in this project that simply contains an iframe that loads the gh-pages deployed version which is [here](http://ritec.github.io/globi/). Depending on how polished the bipartite graph is, the new view could be labeled "Labs" or "Experiments" to make it clear if this is not a finished product.

Another possibility is to link to it from either the Network or Explore view, something like "click here to explore an alternate visualization etc."

The more long term solution would be to "angularize" the bipartite vis, separating it into controller, service and directive similar to the column network graph, but this could be a future enhancement.

**Comment by ritec** [comment]
I will attempt to give this a shot once the core functionality is built and finalized. That said I will have to watch some Angular tutorials. Thanks!

**Comment by danielabar** [comment]
Sure thing, otherwise I can help you. Basically you would add another route/view entry in app.js, may not even need a controller. Then in the view template, put your iframe in there.

**Comment by ritec** [comment]
I will be tackling this feature today, hopefully will have it done before 8. I'll have it in a separate branch? and then we can decide if we want to merge it or not. Does that sounds good?
