### ISSUE TITLE
Replace Network link on cards with explicit Network link in Explore dock

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#44]
This will address #27 (feedback from Sean) and #30 (confusion about what clicking Network from a search result card does).

Remove Network link from cards.

Instead in the Explore Dock, after a species is selected AND interaction results are found, then the dock should show either a link or action button with some text such as "View Network".

Clicking the action button should transition to the Network view (we have code that does this already in main.js, except that it responds to an event emitted from the card, instead, it should be an explicit function available on the scope).

**Comment by danielabar** [comment]
Hi Peter, I've assigned to you, if you have time to work on this. Let me  know if you have any questions.

**Comment by psmacmur** [comment]
I'll get started on this today.

**Comment by danielabar** [comment]
Awesome, thanks!

**Comment by danielabar** [comment]
One other thought I had to make this portion of the exploration more clear, in the dock beside the card, it could say something like:
Click on one of the interactions on the card OR view network.

Just in case it's not immediately obvious to the user that they should click on one of the "Eats", "Eaten by" etc. to proceed.

**Comment by danielabar** [comment]
I think this can be closed?

**Comment by psmacmur** [comment]
Fixed as of #62
