### ISSUE TITLE
Card layout

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#5]
Styling changes to improve the card layout.

**Comment by danielabar** [comment]
One thing I notice is when the Explore page first loads, a blank card is briefly displayed, then disappears. It didn't used to do that before. It's not a big deal but would be nice for the card not to show until the user has selected a taxon.

**Comment by psmacmur** [comment]
Good catch, I'll have a look later; its probably due to the visibility attribute I added.

**Comment by psmacmur** [comment]
May I close this one too?

**Comment by danielabar** [comment]
absolutely

**Comment by psmacmur** [comment]
Fixed as of #62 or so
