### ISSUE TITLE
Linkback edges no longer responding to hover

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#84]
I think this used to work but now its not. When user hovers over any edge in the network, including linkbacks, the edge should change to a lightish blue color and get wider as a visual cue that its clickable. The dotted linkback edges are no longer doing this (although they are still clickable)

**Comment by danielabar** [comment]
I think this can be closed?

**Comment by psmacmur** [comment]
Ah yes, thanks for merging
