### ISSUE TITLE
Error: Invalid value for <path> attribute d="M0,-4L10,0L0,4L10"

### ISSUE THREAD

**Issue by danielabar** [danielabar/globi-proto#85]
When network graph is first rendered, this error shows in console

```
Error: Invalid value for <path> attribute d="M0,-4L10,0L0,4L10"
```

Everything seems to be working though, but it would be nice to clean this up so we don't get used to ignoring errors in the console.

**Comment by danielabar** [comment]
I think this can be closed?

**Comment by psmacmur** [comment]
Indeed; thanks for merging
